### ISSUE TITLE
Multiple symbols in superscript 

### ISSUE THREAD

**Issue by Joriswillems** [acorbe/autogpy#1]
@acorbe 

A superscript with a single variable (x^a) works. However, multiple variables (x^{abc}) in superscripts gives an error when using autognuplot in python, see screenshot.

Adapting the fig__.core.gnu file and hitting make from the command line does indeed produce the desired result. The error is hence python/autognuplot related.

The code:
p1.p_generic(r'u 1 : 2 w points t "Synthetic data **$\\sim N^{-0.23}$**" lt 1 lw 2 ', nb_samples, xbar)

<img width="1052" alt="Schermafbeelding 2019-07-03 om 15 48 32" src="https://user-images.githubusercontent.com/37370392/60596811-070ffc00-9daa-11e9-837c-93eeb744e94c.png">

**Comment by acorbe** [comment]
thanks

ok. this depends on the fact that the string template engine uses curly brackets as latex does. Need to figure out something.

**Comment by acorbe** [comment]
This is solved from version 0.2 by this line and surroundings https://github.com/acorbe/autogpy/blob/a040ff2211e3e849c05634c224644d95a61cac6a/autogpy/autognuplot.py#L631

thanks for reporting

![image](https://user-images.githubusercontent.com/2300692/89737035-4b220580-da6e-11ea-9ac4-1bc251a1a07b.png)
